name: Main
on: [push]

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "github-action-maven-release"

      - name: Local Action
        uses: ./github-action-maven-release